### ISSUE TITLE
Submit to wordpress.org

### ISSUE THREAD

**Issue by rohmann** [rohmann/global-smtp#10]
I'd like to get this on the wordpress.org repo at some point. Before then, here are some proposed changes:

* Rename to: wp-global-smtp (because it works on standard sites as well)
* Make a standard plugin by default instead of an mu plugin. (although it will still work if installed that way)
* Add an admin interface that gives you a box to  copy/paste a sample configuration if no constants are detected.

This likely won't be for a few weeks when I have some more time. Until then, I'm open to feedback from anyone using the plugin presently.

**Comment by Surbma** [comment]
Great step forward. If you create a Git repo for the new plugin, I would be happy to collaborate from the beginning to get it working as soon as possible.

**Comment by rohmann** [comment]
@Surbma I just renamed this repo and updated the README.md. Feel free to send a PR here with changes.

**Comment by rohmann** [comment]
So I normally wouldn't do this, but because the plugin was renamed, and it's a pretty small project I just removed all the old tagged releases and reset to version 1.0.

Once approved on wordpress.org, I'll tag a new 1.0 on this repo.

**Comment by rohmann** [comment]
Update: Had some time this weekend, and I've submitted it to the repo.

**Comment by rohmann** [comment]
Done: https://wordpress.org/plugins/global-smtp/

**Comment by Surbma** [comment]
Great news. Thank you for your work!
