### ISSUE TITLE
Network activated 2.3.0 version is not working for me

### ISSUE THREAD

**Issue by Surbma** [rohmann/global-smtp#12]
Hi,

I just extended your original mu-plugin to have admin menu and for the localization. I have network activated it, but it seems it doesn't send the mail.

Can it be because it is loading too late?

I'll be testing it on my other installs, but I wanted to let you know this issue.

**Comment by rohmann** [comment]
@Surbma 

It's been working on multisite for me since recent updates. I've made a few more updates in preparation for submitting to wordpress.org. I've tested the master branch and it's still working ok right now.
